// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/kdotwei/hpl-scoreboard/internal/db"
	mock "github.com/stretchr/testify/mock"

	service "github.com/kdotwei/hpl-scoreboard/internal/service"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateScore provides a mock function with given fields: ctx, arg
func (_m *Service) CreateScore(ctx context.Context, arg service.CreateScoreParams) (*db.Score, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateScore")
	}

	var r0 *db.Score
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateScoreParams) (*db.Score, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateScoreParams) *db.Score); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Score)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreateScoreParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
