// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Score struct {
	ID           pgtype.UUID `json:"id"`
	UserID       string      `json:"user_id"`
	Gflops       float64     `json:"gflops"`
	ProblemSizeN int32       `json:"problem_size_n"`
	BlockSizeNb  int32       `json:"block_size_nb"`
	SubmittedAt  time.Time   `json:"submitted_at"`
}
