// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountTotalScores(ctx context.Context) (int64, error)
	CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error)
	ListScoresWithPagination(ctx context.Context, arg ListScoresWithPaginationParams) ([]Score, error)
	ListTopScores(ctx context.Context, arg ListTopScoresParams) ([]Score, error)
}

var _ Querier = (*Queries)(nil)
