// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error)
	ListTopScores(ctx context.Context, limit int32) ([]Score, error)
}

var _ Querier = (*Queries)(nil)
