// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: score.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTotalScores = `-- name: CountTotalScores :one
SELECT COUNT(*) FROM scores
`

func (q *Queries) CountTotalScores(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalScores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScore = `-- name: CreateScore :one
INSERT INTO scores (
  user_id,
  gflops,
  problem_size_n,
  block_size_nb,
  linux_username,
  n,
  nb,
  p,
  q,
  execution_time,
  submitted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, gflops, problem_size_n, block_size_nb, submitted_at, linux_username, n, nb, p, q, execution_time
`

type CreateScoreParams struct {
	UserID        string    `json:"user_id"`
	Gflops        float64   `json:"gflops"`
	ProblemSizeN  int32     `json:"problem_size_n"`
	BlockSizeNb   int32     `json:"block_size_nb"`
	LinuxUsername string    `json:"linux_username"`
	N             int32     `json:"n"`
	Nb            int32     `json:"nb"`
	P             int32     `json:"p"`
	Q             int32     `json:"q"`
	ExecutionTime float64   `json:"execution_time"`
	SubmittedAt   time.Time `json:"submitted_at"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.UserID,
		arg.Gflops,
		arg.ProblemSizeN,
		arg.BlockSizeNb,
		arg.LinuxUsername,
		arg.N,
		arg.Nb,
		arg.P,
		arg.Q,
		arg.ExecutionTime,
		arg.SubmittedAt,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Gflops,
		&i.ProblemSizeN,
		&i.BlockSizeNb,
		&i.SubmittedAt,
		&i.LinuxUsername,
		&i.N,
		&i.Nb,
		&i.P,
		&i.Q,
		&i.ExecutionTime,
	)
	return i, err
}

const listScoresWithPagination = `-- name: ListScoresWithPagination :many
SELECT id, user_id, gflops, problem_size_n, block_size_nb, submitted_at, linux_username, n, nb, p, q, execution_time FROM scores
WHERE ($1::uuid IS NULL OR id < $1)
ORDER BY gflops DESC, id DESC
LIMIT $2
`

type ListScoresWithPaginationParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListScoresWithPagination(ctx context.Context, arg ListScoresWithPaginationParams) ([]Score, error) {
	rows, err := q.db.Query(ctx, listScoresWithPagination, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Gflops,
			&i.ProblemSizeN,
			&i.BlockSizeNb,
			&i.SubmittedAt,
			&i.LinuxUsername,
			&i.N,
			&i.Nb,
			&i.P,
			&i.Q,
			&i.ExecutionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopScores = `-- name: ListTopScores :many
SELECT id, user_id, gflops, problem_size_n, block_size_nb, submitted_at, linux_username, n, nb, p, q, execution_time FROM scores
ORDER BY gflops DESC
LIMIT $1 OFFSET $2
`

type ListTopScoresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTopScores(ctx context.Context, arg ListTopScoresParams) ([]Score, error) {
	rows, err := q.db.Query(ctx, listTopScores, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Gflops,
			&i.ProblemSizeN,
			&i.BlockSizeNb,
			&i.SubmittedAt,
			&i.LinuxUsername,
			&i.N,
			&i.Nb,
			&i.P,
			&i.Q,
			&i.ExecutionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
