// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: score.sql

package db

import (
	"context"
	"time"
)

const createScore = `-- name: CreateScore :one
INSERT INTO scores (
  user_id,
  gflops,
  problem_size_n,
  block_size_nb,
  submitted_at
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, user_id, gflops, problem_size_n, block_size_nb, submitted_at
`

type CreateScoreParams struct {
	UserID       string    `json:"user_id"`
	Gflops       float64   `json:"gflops"`
	ProblemSizeN int32     `json:"problem_size_n"`
	BlockSizeNb  int32     `json:"block_size_nb"`
	SubmittedAt  time.Time `json:"submitted_at"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.UserID,
		arg.Gflops,
		arg.ProblemSizeN,
		arg.BlockSizeNb,
		arg.SubmittedAt,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Gflops,
		&i.ProblemSizeN,
		&i.BlockSizeNb,
		&i.SubmittedAt,
	)
	return i, err
}

const listTopScores = `-- name: ListTopScores :many
SELECT id, user_id, gflops, problem_size_n, block_size_nb, submitted_at FROM scores
ORDER BY gflops DESC
LIMIT $1
`

func (q *Queries) ListTopScores(ctx context.Context, limit int32) ([]Score, error) {
	rows, err := q.db.Query(ctx, listTopScores, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Gflops,
			&i.ProblemSizeN,
			&i.BlockSizeNb,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
